### ISSUE TITLE
EJS snippets don't work in certain places

### ISSUE THREAD

**Issue by JoelDorrington** [theranbrig/ejs-snippets#3]
I've noticed that ejs snippets don't work between quotes such as html attributes, nor between style tags or script tags

**Comment by theranbrig** [comment]
I believe that that is a setting is a VS Code setting.  I believe that you may want to take a look at your quickSuggestions setting.  I think mine is set to:

```json
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  },
```

**Comment by JoelDorrington** [comment]
Thanks for getting back quicky.
That's fixed it for me inside strings, thanks. However the issue remains while coding between style or script tags.

**Comment by theranbrig** [comment]
Check out [EJS Language Support](https://bit.ly/3a9b7Qy).  This is baked into that.
