### ISSUE TITLE
help

### ISSUE THREAD

**Issue by benjamin83690** [theranbrig/ejs-snippets#4]
i can't make your extensions work ... ejs + tab nothing is happennig !
I am a beginner, I may not have done what was needed? I just installed the app and nothing happens

**Comment by the1abel** [comment]
I just installed this extension and reloaded, but it also isn't working for me.  I checked my editor.quickSuggestions, and they are set as @theranbrig showed in Issue #3.  Any suggestions?

**Comment by theranbrig** [comment]
@benjamin83690 @the1abel Check out [EJS Language Support](https://bit.ly/3a9b7Qy).  This is baked into that.
