### ISSUE TITLE
How can I use the snippets ?

### ISSUE THREAD

**Issue by thiagorodrigu3s** [theranbrig/ejs-snippets#5]
I've tried to debug it on vscode and then I created an ejs file to test using the snippets but that's still not working.

**Comment by Betanu701** [comment]
@thRodrigues7 If you are using [EJS Language Support](https://bit.ly/3a9b7Qy) extension. These have been baked in as of version 1.2 If they do not work, read the read me as I have included steps to make sure it works.

**Comment by theranbrig** [comment]
I would follow @Betanu701.
